# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "caltuco-llc-remote-state"
    dynamodb_table = "caltuco-llc-remote-state-lock"
    encrypt        = true
    key            = "./terraform.tfstate"
    profile        = "caltuco_aws"
    region         = "us-east-1"
  }
}
